-- SQL Updates for Case Differences
-- Generated from name_comparison_report.json
-- Total records: 111

BEGIN;

UPDATE players SET gamertag = 'Afromaker' WHERE LOWER(gamertag) = LOWER('afromaker');
UPDATE players SET gamertag = 'Airasaf' WHERE LOWER(gamertag) = LOWER('AirAsaf');
UPDATE players SET gamertag = 'AJ lillard' WHERE LOWER(gamertag) = LOWER('AJ Lillard');
UPDATE players SET gamertag = 'Alsmoovee' WHERE LOWER(gamertag) = LOWER('AlSmoovee');
UPDATE players SET gamertag = 'AustinReegs' WHERE LOWER(gamertag) = LOWER('AUSTINREEGS');
UPDATE players SET gamertag = 'Ayeeyoocorb' WHERE LOWER(gamertag) = LOWER('AyeeyooCorb');
UPDATE players SET gamertag = 'Ayrabb-' WHERE LOWER(gamertag) = LOWER('ayrabb-');
UPDATE players SET gamertag = 'Belichecked' WHERE LOWER(gamertag) = LOWER('BELICHECKED');
UPDATE players SET gamertag = 'cameraflip' WHERE LOWER(gamertag) = LOWER('CameraFlip');
UPDATE players SET gamertag = 'CantGuardRobTTV' WHERE LOWER(gamertag) = LOWER('CantguardrobTTV');
UPDATE players SET gamertag = 'CB13OnTwitch' WHERE LOWER(gamertag) = LOWER('CB13onTwitch');
UPDATE players SET gamertag = 'Chriskickz' WHERE LOWER(gamertag) = LOWER('ChrisKickz');
UPDATE players SET gamertag = 'Coachwhogamesttv' WHERE LOWER(gamertag) = LOWER('CoachWhoGamesTTV');
UPDATE players SET gamertag = 'Come on Duuude' WHERE LOWER(gamertag) = LOWER('Come on duuude');
UPDATE players SET gamertag = 'Cxhzie' WHERE LOWER(gamertag) = LOWER('cxhzie');
UPDATE players SET gamertag = 'D redd2x' WHERE LOWER(gamertag) = LOWER('d redd2x');
UPDATE players SET gamertag = 'Daehonncho' WHERE LOWER(gamertag) = LOWER('DaeHonncho');
UPDATE players SET gamertag = 'Damnn_CB' WHERE LOWER(gamertag) = LOWER('Damnn_cb');
UPDATE players SET gamertag = 'Dcash ny' WHERE LOWER(gamertag) = LOWER('Dcash NY');
UPDATE players SET gamertag = 'Deadpoolk' WHERE LOWER(gamertag) = LOWER('DeadpoolK');
UPDATE players SET gamertag = 'DonFloatinn' WHERE LOWER(gamertag) = LOWER('donfloatinn');
UPDATE players SET gamertag = 'DonJulioTV' WHERE LOWER(gamertag) = LOWER('DonJulioTv');
UPDATE players SET gamertag = 'Duffyszn2k' WHERE LOWER(gamertag) = LOWER('DuffySzn2k');
UPDATE players SET gamertag = 'Dungardoctor' WHERE LOWER(gamertag) = LOWER('dungardoctor');
UPDATE players SET gamertag = 'Dynastyxcjay' WHERE LOWER(gamertag) = LOWER('DynastyxCjay');
UPDATE players SET gamertag = 'Dynastyxkdub2k' WHERE LOWER(gamertag) = LOWER('DynastyxKdub2k');
UPDATE players SET gamertag = 'exploitgawdtv--' WHERE LOWER(gamertag) = LOWER('ExploitGawdTV--');
UPDATE players SET gamertag = 'FakeStepk' WHERE LOWER(gamertag) = LOWER('FakeStepK');
UPDATE players SET gamertag = 'Feelinoc' WHERE LOWER(gamertag) = LOWER('FeeliNoc');
UPDATE players SET gamertag = 'Fiftyclip' WHERE LOWER(gamertag) = LOWER('FiftyClip');
UPDATE players SET gamertag = 'freakytretv' WHERE LOWER(gamertag) = LOWER('freakytreTV');
UPDATE players SET gamertag = 'Futurewyd' WHERE LOWER(gamertag) = LOWER('FutureWyd');
UPDATE players SET gamertag = 'goldenboy YP' WHERE LOWER(gamertag) = LOWER('GoldenBoy YP');
UPDATE players SET gamertag = 'Guess passes' WHERE LOWER(gamertag) = LOWER('Guess Passes');
UPDATE players SET gamertag = 'Hey feared' WHERE LOWER(gamertag) = LOWER('Hey Feared');
UPDATE players SET gamertag = 'iA-MOTH' WHERE LOWER(gamertag) = LOWER('IA-MOTH');
UPDATE players SET gamertag = 'iball_splash' WHERE LOWER(gamertag) = LOWER('iBall_Splash');
UPDATE players SET gamertag = 'Iiithexmaniii' WHERE LOWER(gamertag) = LOWER('IIITheXmaNIII
');
UPDATE players SET gamertag = 'IKostaGoated' WHERE LOWER(gamertag) = LOWER('iKostaGoated');
UPDATE players SET gamertag = 'ill-Dante-lli' WHERE LOWER(gamertag) = LOWER('Ill-DANTE-llI');
UPDATE players SET gamertag = 'Imbig2x' WHERE LOWER(gamertag) = LOWER('IMBIG2X');
UPDATE players SET gamertag = 'Immapopper' WHERE LOWER(gamertag) = LOWER('ImmaPopper');
UPDATE players SET gamertag = 'Imvardii' WHERE LOWER(gamertag) = LOWER('ImVardii');
UPDATE players SET gamertag = 'Iplayhashttv' WHERE LOWER(gamertag) = LOWER('iPlayHashTTV');
UPDATE players SET gamertag = 'Jawndog781' WHERE LOWER(gamertag) = LOWER('JawnDog781');
UPDATE players SET gamertag = 'jayadebayo' WHERE LOWER(gamertag) = LOWER('JayAdebayo');
UPDATE players SET gamertag = 'jayotoocold' WHERE LOWER(gamertag) = LOWER('Jayotoocold');
UPDATE players SET gamertag = 'jaysnagss' WHERE LOWER(gamertag) = LOWER('JaySnagss');
UPDATE players SET gamertag = 'Jery05' WHERE LOWER(gamertag) = LOWER('JERY05');
UPDATE players SET gamertag = 'JGxCashout919' WHERE LOWER(gamertag) = LOWER('JGXCASHOUT919');
UPDATE players SET gamertag = 'jhabaree' WHERE LOWER(gamertag) = LOWER('JHABAREE');
UPDATE players SET gamertag = 'Jitzeus' WHERE LOWER(gamertag) = LOWER('JitZeus');
UPDATE players SET gamertag = 'Jjayvis' WHERE LOWER(gamertag) = LOWER('jjayvis');
UPDATE players SET gamertag = 'Joe_pepi' WHERE LOWER(gamertag) = LOWER('Joe_Pepi');
UPDATE players SET gamertag = 'Johnnyfresh21_' WHERE LOWER(gamertag) = LOWER('JohnnyFresh21_');
UPDATE players SET gamertag = 'Juice_uchiha' WHERE LOWER(gamertag) = LOWER('Juice_Uchiha');
UPDATE players SET gamertag = 'KokiJames' WHERE LOWER(gamertag) = LOWER('Kokijames');
UPDATE players SET gamertag = 'Kyng Gaza' WHERE LOWER(gamertag) = LOWER('KYNG Gaza');
UPDATE players SET gamertag = 'Laayupk' WHERE LOWER(gamertag) = LOWER('laayupk');
UPDATE players SET gamertag = 'Laidbacksv' WHERE LOWER(gamertag) = LOWER('LaidbackSV');
UPDATE players SET gamertag = 'LethalTrxster' WHERE LOWER(gamertag) = LOWER('LeThaLTrXsTeR');
UPDATE players SET gamertag = 'lilShowz' WHERE LOWER(gamertag) = LOWER('LilShowz');
UPDATE players SET gamertag = 'M1keyTheGem40' WHERE LOWER(gamertag) = LOWER('M1keytheGEM40');
UPDATE players SET gamertag = 'Mallorybellaire' WHERE LOWER(gamertag) = LOWER('MalloryBellaire');
UPDATE players SET gamertag = 'Manzebk' WHERE LOWER(gamertag) = LOWER('ManzEbk');
UPDATE players SET gamertag = 'Mrsellyourshixx' WHERE LOWER(gamertag) = LOWER('MRSellYourshiXX');
UPDATE players SET gamertag = 'NayRko' WHERE LOWER(gamertag) = LOWER('NayRKO');
UPDATE players SET gamertag = 'Newfound Joy' WHERE LOWER(gamertag) = LOWER('NewFound Joy');
UPDATE players SET gamertag = 'nxtgenstreetTTV' WHERE LOWER(gamertag) = LOWER('NxtgenstreetTTV');
UPDATE players SET gamertag = 'Oc-ern-' WHERE LOWER(gamertag) = LOWER('OC-ERN-');
UPDATE players SET gamertag = 'Ocktheshooter' WHERE LOWER(gamertag) = LOWER('OckTheShooter');
UPDATE players SET gamertag = 'ohdonn' WHERE LOWER(gamertag) = LOWER('OhDonn');
UPDATE players SET gamertag = 'orbitsplash' WHERE LOWER(gamertag) = LOWER('OrbitSplash');
UPDATE players SET gamertag = 'PattyMil' WHERE LOWER(gamertag) = LOWER('pattymil');
UPDATE players SET gamertag = 'Pgjeree' WHERE LOWER(gamertag) = LOWER('pgjeree');
UPDATE players SET gamertag = 'pGrinchy TTv' WHERE LOWER(gamertag) = LOWER('pGrinchy TTV');
UPDATE players SET gamertag = 'Polomanofearth' WHERE LOWER(gamertag) = LOWER('polomanofearth');
UPDATE players SET gamertag = 'Repowrld-' WHERE LOWER(gamertag) = LOWER('RepoWrld-');
UPDATE players SET gamertag = 'Shalla-Bal' WHERE LOWER(gamertag) = LOWER('SHALLA-BAL');
UPDATE players SET gamertag = 'Shmaku' WHERE LOWER(gamertag) = LOWER('SHMAKU');
UPDATE players SET gamertag = 'sikko' WHERE LOWER(gamertag) = LOWER('Sikko');
UPDATE players SET gamertag = 'Solotry' WHERE LOWER(gamertag) = LOWER('SoloTry');
UPDATE players SET gamertag = 'Spookynugget24' WHERE LOWER(gamertag) = LOWER('SPOOKYNUGGET24');
UPDATE players SET gamertag = 'Stackinstops' WHERE LOWER(gamertag) = LOWER('StackinStops');
UPDATE players SET gamertag = 'Stammm7' WHERE LOWER(gamertag) = LOWER('stammm7');
UPDATE players SET gamertag = 'Swaycashh' WHERE LOWER(gamertag) = LOWER('swayCashh');
UPDATE players SET gamertag = 'SynnSuave' WHERE LOWER(gamertag) = LOWER('Synnsuave');
UPDATE players SET gamertag = 'Temikal' WHERE LOWER(gamertag) = LOWER('TeMikal');
UPDATE players SET gamertag = 'Tfjuice' WHERE LOWER(gamertag) = LOWER('tfjuice');
UPDATE players SET gamertag = 'TheParanoidduck' WHERE LOWER(gamertag) = LOWER('TheParanoidDuck');
UPDATE players SET gamertag = 'TmChris2k' WHERE LOWER(gamertag) = LOWER('TmChris2K');
UPDATE players SET gamertag = 'Tonyfrmthe6ix' WHERE LOWER(gamertag) = LOWER('TonyFrmThe6ix');
UPDATE players SET gamertag = 'TTV 4kJayW' WHERE LOWER(gamertag) = LOWER('TTV 4KJayW');
UPDATE players SET gamertag = 'VJackey' WHERE LOWER(gamertag) = LOWER('vJackey');
UPDATE players SET gamertag = 'Walksum-' WHERE LOWER(gamertag) = LOWER('WalkSum-');
UPDATE players SET gamertag = 'wassam5ive' WHERE LOWER(gamertag) = LOWER('Wassam5ive');
UPDATE players SET gamertag = 'Wavyrose' WHERE LOWER(gamertag) = LOWER('wavyrose');
UPDATE players SET gamertag = 'winningNgaining' WHERE LOWER(gamertag) = LOWER('WINNINGNGAINING');
UPDATE players SET gamertag = 'XBrixton_' WHERE LOWER(gamertag) = LOWER('xBrixton_');
UPDATE players SET gamertag = 'XFatboyTrae' WHERE LOWER(gamertag) = LOWER('xFatboyTrae');
UPDATE players SET gamertag = 'XFrostFades' WHERE LOWER(gamertag) = LOWER('xFrostfades');
UPDATE players SET gamertag = 'xfundayy-' WHERE LOWER(gamertag) = LOWER('xFundayy-');
UPDATE players SET gamertag = 'xkingsworld' WHERE LOWER(gamertag) = LOWER('xKingsworld');
UPDATE players SET gamertag = 'Xmajxx' WHERE LOWER(gamertag) = LOWER('xmajxx');
UPDATE players SET gamertag = 'xojask' WHERE LOWER(gamertag) = LOWER('xoJask');
UPDATE players SET gamertag = 'Yaegoated' WHERE LOWER(gamertag) = LOWER('YaeGoated');
UPDATE players SET gamertag = 'Yikki-Za' WHERE LOWER(gamertag) = LOWER('Yikki-za');
UPDATE players SET gamertag = 'YouxBop' WHERE LOWER(gamertag) = LOWER('YouxBOP');
UPDATE players SET gamertag = 'yvesgbump' WHERE LOWER(gamertag) = LOWER('YveSGbump');
UPDATE players SET gamertag = 'Zendrawlin' WHERE LOWER(gamertag) = LOWER('ZenDrawlin');
UPDATE players SET gamertag = 'ZiZoe' WHERE LOWER(gamertag) = LOWER('Zizoe');

COMMIT;
