-- SQL Updates for Case Differences
-- Generated from name_comparison_report.json
-- Total records: 227

BEGIN;

UPDATE players SET gamertag = 'Manny Taft' WHERE LOWER(gamertag) = LOWER('MannyTAFT');
UPDATE players SET gamertag = 'Chris kickz' WHERE LOWER(gamertag) = LOWER('Chriskickz');
UPDATE players SET gamertag = 'Repowrld_' WHERE LOWER(gamertag) = LOWER('Repowrld-');
UPDATE players SET gamertag = 'Jairo2k_' WHERE LOWER(gamertag) = LOWER('Jairo2k');
UPDATE players SET gamertag = 'Sideshowsin' WHERE LOWER(gamertag) = LOWER('SideshowSin');
UPDATE players SET gamertag = 'WILLOSAUCE' WHERE LOWER(gamertag) = LOWER('Willosauce');
UPDATE players SET gamertag = 'RichOffGrass-' WHERE LOWER(gamertag) = LOWER('RICHOFFGRASSS-');
UPDATE players SET gamertag = 'JayyQP' WHERE LOWER(gamertag) = LOWER('JAYYQP');
UPDATE players SET gamertag = 'xMambaout' WHERE LOWER(gamertag) = LOWER('xMambaOut');
UPDATE players SET gamertag = 'Can''t Skill' WHERE LOWER(gamertag) = LOWER('Cant Skill');
UPDATE players SET gamertag = 'yjexy' WHERE LOWER(gamertag) = LOWER('yJexy');
UPDATE players SET gamertag = 'imxLuke' WHERE LOWER(gamertag) = LOWER('ImxLuke');
UPDATE players SET gamertag = 'Vmpya' WHERE LOWER(gamertag) = LOWER('vmpya');
UPDATE players SET gamertag = 'Xxcityboyyxx' WHERE LOWER(gamertag) = LOWER('XxCityBoyyxX');
UPDATE players SET gamertag = 'Whotfisbleu' WHERE LOWER(gamertag) = LOWER('WhoTFisBLEU');
UPDATE players SET gamertag = 'Leeky_Lo' WHERE LOWER(gamertag) = LOWER('Leeky_lo');
UPDATE players SET gamertag = 'StopJDUB' WHERE LOWER(gamertag) = LOWER('StopJDub');
UPDATE players SET gamertag = 'lolAmiri' WHERE LOWER(gamertag) = LOWER('LOLAMIRI');
UPDATE players SET gamertag = 'DsavGetBuckets-' WHERE LOWER(gamertag) = LOWER('DsavGetBuckets--');
UPDATE players SET gamertag = 'jaytoocold' WHERE LOWER(gamertag) = LOWER('jayotoocold');
UPDATE players SET gamertag = 'Cristiangotzen' WHERE LOWER(gamertag) = LOWER('CristianGotZen');
UPDATE players SET gamertag = 'Tighallshot' WHERE LOWER(gamertag) = LOWER('TightAllShot');
UPDATE players SET gamertag = 'FirstYezzy' WHERE LOWER(gamertag) = LOWER('First Yezzy');
UPDATE players SET gamertag = 'goldenboyyp' WHERE LOWER(gamertag) = LOWER('goldenboy YP');
UPDATE players SET gamertag = 'JackNFO' WHERE LOWER(gamertag) = LOWER('JACKNFO');
UPDATE players SET gamertag = 'ryevsrah' WHERE LOWER(gamertag) = LOWER('Rye vs Rah');
UPDATE players SET gamertag = 'Br0nx718' WHERE LOWER(gamertag) = LOWER('BR0NX 718');
UPDATE players SET gamertag = 'TanDurant' WHERE LOWER(gamertag) = LOWER('TANdurant');
UPDATE players SET gamertag = 'TheKoko__' WHERE LOWER(gamertag) = LOWER('TheKoKo_');
UPDATE players SET gamertag = 'Certified N8' WHERE LOWER(gamertag) = LOWER('CERTIFIED N8');
UPDATE players SET gamertag = 'Need IQ Test' WHERE LOWER(gamertag) = LOWER('NEED IQ TEST');
UPDATE players SET gamertag = 'Juulz Newman' WHERE LOWER(gamertag) = LOWER('JUULZ NEWMAN');
UPDATE players SET gamertag = 'ReallyAnt' WHERE LOWER(gamertag) = LOWER('REALLYANT');
UPDATE players SET gamertag = 'Kingyup' WHERE LOWER(gamertag) = LOWER('KINGYUP');
UPDATE players SET gamertag = 'Bootot' WHERE LOWER(gamertag) = LOWER('BOOTOT');
UPDATE players SET gamertag = 'Stkkn' WHERE LOWER(gamertag) = LOWER('stkkn');
UPDATE players SET gamertag = 'llscottiell' WHERE LOWER(gamertag) = LOWER('llscottieell');
UPDATE players SET gamertag = 'buckethatbean' WHERE LOWER(gamertag) = LOWER('BucketHatBean');
UPDATE players SET gamertag = 'youngmannirs' WHERE LOWER(gamertag) = LOWER('YoungmannIRS');
UPDATE players SET gamertag = 'ztbang4lyfee4' WHERE LOWER(gamertag) = LOWER('ZTBang4lyfee4');
UPDATE players SET gamertag = 'Shadowswagger25' WHERE LOWER(gamertag) = LOWER('shadowswagger25');
UPDATE players SET gamertag = 'Im kxngB' WHERE LOWER(gamertag) = LOWER('im kxngB');
UPDATE players SET gamertag = 'CGM madman' WHERE LOWER(gamertag) = LOWER('CGM MadMan');
UPDATE players SET gamertag = 'CGM Kashflow' WHERE LOWER(gamertag) = LOWER('CGM KashFlow');
UPDATE players SET gamertag = 'Im dirty3x' WHERE LOWER(gamertag) = LOWER('im dirty3x');
UPDATE players SET gamertag = 'CGM slayed' WHERE LOWER(gamertag) = LOWER('CGM SLAYED');
UPDATE players SET gamertag = 'Lockvino' WHERE LOWER(gamertag) = LOWER('LOCKVINO');
UPDATE players SET gamertag = 'TikTok-Pablo' WHERE LOWER(gamertag) = LOWER('Tiktokpablo');
UPDATE players SET gamertag = 'ItsK3nnyTV' WHERE LOWER(gamertag) = LOWER('Itsk3nnyttv');
UPDATE players SET gamertag = 'Swann__2KL' WHERE LOWER(gamertag) = LOWER('Swann_2KL');
UPDATE players SET gamertag = 'iUyscuti' WHERE LOWER(gamertag) = LOWER('IUyScuti');
UPDATE players SET gamertag = 'Pluckiana' WHERE LOWER(gamertag) = LOWER('pluckiana');
UPDATE players SET gamertag = 'SouthernSlayer' WHERE LOWER(gamertag) = LOWER('SOUTHERNSLAYER');
UPDATE players SET gamertag = 'GabeDaGriper' WHERE LOWER(gamertag) = LOWER('GABEDAGRIPER');
UPDATE players SET gamertag = 'Set A Miyagi' WHERE LOWER(gamertag) = LOWER('SET A MIYAGI');
UPDATE players SET gamertag = 'Bigske215' WHERE LOWER(gamertag) = LOWER('BigSke215');
UPDATE players SET gamertag = 'YoJWill' WHERE LOWER(gamertag) = LOWER('YOJWILL');
UPDATE players SET gamertag = 'HarryDotter_25' WHERE LOWER(gamertag) = LOWER('HARRYDOTTER_25');
UPDATE players SET gamertag = 'Truckn_Flee' WHERE LOWER(gamertag) = LOWER('TRUCK_FLEE');
UPDATE players SET gamertag = 'TylerBoudreaux' WHERE LOWER(gamertag) = LOWER('TYLERBOUDREAUX');
UPDATE players SET gamertag = 'Lawrichx' WHERE LOWER(gamertag) = LOWER('LawRichx');
UPDATE players SET gamertag = 'Getmyballs' WHERE LOWER(gamertag) = LOWER('GetMyBalls');
UPDATE players SET gamertag = 'Ayejay' WHERE LOWER(gamertag) = LOWER('AYEJAY');
UPDATE players SET gamertag = 'Hwillz' WHERE LOWER(gamertag) = LOWER('HWILLZ');
UPDATE players SET gamertag = 'Juggyalife' WHERE LOWER(gamertag) = LOWER('JUGGYALIFE');
UPDATE players SET gamertag = 'Setto' WHERE LOWER(gamertag) = LOWER('SETTO');
UPDATE players SET gamertag = 'Peej' WHERE LOWER(gamertag) = LOWER('PEEJ');
UPDATE players SET gamertag = 'Lo_bucket2K' WHERE LOWER(gamertag) = LOWER('Lo Bucket2k');
UPDATE players SET gamertag = 'soso_933' WHERE LOWER(gamertag) = LOWER('soso 933');
UPDATE players SET gamertag = 'ay_lon' WHERE LOWER(gamertag) = LOWER('Ay_lon');
UPDATE players SET gamertag = 'dparty' WHERE LOWER(gamertag) = LOWER('DPARTY');
UPDATE players SET gamertag = 'Itstvo' WHERE LOWER(gamertag) = LOWER('ItsTVO');
UPDATE players SET gamertag = 'TNTxDynomike' WHERE LOWER(gamertag) = LOWER('TNTxDynoMike');
UPDATE players SET gamertag = 'SpilledMyWock-' WHERE LOWER(gamertag) = LOWER('SpilledMyWock');
UPDATE players SET gamertag = 'Gloccs out' WHERE LOWER(gamertag) = LOWER('Gloccs Out');
UPDATE players SET gamertag = 'Alwayzextra' WHERE LOWER(gamertag) = LOWER('Alwayz extra');
UPDATE players SET gamertag = 'Tris4kt' WHERE LOWER(gamertag) = LOWER('Tris4KT');
UPDATE players SET gamertag = 'Hery__942' WHERE LOWER(gamertag) = LOWER('HERY_942');
UPDATE players SET gamertag = 'Rivohasina' WHERE LOWER(gamertag) = LOWER('rivohasina');
UPDATE players SET gamertag = 'SettegastBub' WHERE LOWER(gamertag) = LOWER('SettegasBub');
UPDATE players SET gamertag = 'chaseisbeast' WHERE LOWER(gamertag) = LOWER('chaseisabeast');
UPDATE players SET gamertag = 'itsboot' WHERE LOWER(gamertag) = LOWER('ItsBoot');
UPDATE players SET gamertag = 'Saverx1176' WHERE LOWER(gamertag) = LOWER('Saver x1176');
UPDATE players SET gamertag = 'Isnt aj' WHERE LOWER(gamertag) = LOWER('isnt Aj');
UPDATE players SET gamertag = 'Noewitzki' WHERE LOWER(gamertag) = LOWER('NOEWITZKI');
UPDATE players SET gamertag = 'Boofiq' WHERE LOWER(gamertag) = LOWER('BOOFiQ');
UPDATE players SET gamertag = 'Itz_Gmac' WHERE LOWER(gamertag) = LOWER('itZGmac');
UPDATE players SET gamertag = 'BallLikeSeem' WHERE LOWER(gamertag) = LOWER('BALLLIKESEEM');
UPDATE players SET gamertag = 'Stexey Boa' WHERE LOWER(gamertag) = LOWER('STEXEY BOA ');
UPDATE players SET gamertag = 'oSaintsLRD' WHERE LOWER(gamertag) = LOWER('oSaints LRD');
UPDATE players SET gamertag = 'D1 Uglygodk' WHERE LOWER(gamertag) = LOWER('D1UGLYGODK');
UPDATE players SET gamertag = 'BNamous' WHERE LOWER(gamertag) = LOWER('B Namous');
UPDATE players SET gamertag = 'Proof_rR' WHERE LOWER(gamertag) = LOWER('Proof rr');
UPDATE players SET gamertag = 'Create Envy-' WHERE LOWER(gamertag) = LOWER('Create envy');
UPDATE players SET gamertag = 'lAlbertEinstein' WHERE LOWER(gamertag) = LOWER('AlbertEinstein');
UPDATE players SET gamertag = 'L_JMAY_L' WHERE LOWER(gamertag) = LOWER('l JMAY_l');
UPDATE players SET gamertag = 'Flygrayy' WHERE LOWER(gamertag) = LOWER('FlyGrayy');
UPDATE players SET gamertag = 'Drizzygetbusy01' WHERE LOWER(gamertag) = LOWER('drizzygetbusy01');
UPDATE players SET gamertag = 'Bigplay937' WHERE LOWER(gamertag) = LOWER('BigPlay_937');
UPDATE players SET gamertag = 'Hotboikeef28' WHERE LOWER(gamertag) = LOWER('HotBoiKeef28');
UPDATE players SET gamertag = 'iFlexx_48' WHERE LOWER(gamertag) = LOWER('IFLEXX_48');
UPDATE players SET gamertag = 'Melo3pt_' WHERE LOWER(gamertag) = LOWER('Melo3pt');
UPDATE players SET gamertag = 'Goatpgll' WHERE LOWER(gamertag) = LOWER('Goatpg ll');
UPDATE players SET gamertag = 'OMG LOUU' WHERE LOWER(gamertag) = LOWER('OMG Louu');
UPDATE players SET gamertag = 'Onlyfluff' WHERE LOWER(gamertag) = LOWER('OnlyFluff');
UPDATE players SET gamertag = 'Jayy x ots' WHERE LOWER(gamertag) = LOWER('Jayy X OTS');
UPDATE players SET gamertag = 'Poppasmerf-' WHERE LOWER(gamertag) = LOWER('PoppaSmerf-');
UPDATE players SET gamertag = 'TTV4kjayw' WHERE LOWER(gamertag) = LOWER('TTV 4kJayW');
UPDATE players SET gamertag = 'Catchingblessing' WHERE LOWER(gamertag) = LOWER('CatchingBlessing');
UPDATE players SET gamertag = 'Xxmoneycashxx' WHERE LOWER(gamertag) = LOWER('xxmoneycashxx');
UPDATE players SET gamertag = 'Wrd2mymuvvaaa' WHERE LOWER(gamertag) = LOWER('Wrd2MyMuvvaaa');
UPDATE players SET gamertag = 'HennyonNXT' WHERE LOWER(gamertag) = LOWER('HennyOnNXT');
UPDATE players SET gamertag = 'No limit NXT' WHERE LOWER(gamertag) = LOWER('NoLimit NXT');
UPDATE players SET gamertag = 'Swantonj nxt' WHERE LOWER(gamertag) = LOWER('Swantonj NXT');
UPDATE players SET gamertag = 'DiceEmoji' WHERE LOWER(gamertag) = LOWER('DICEEMOJI');
UPDATE players SET gamertag = 'QualityEra' WHERE LOWER(gamertag) = LOWER('QUALITYERA');
UPDATE players SET gamertag = 'NoInterior' WHERE LOWER(gamertag) = LOWER('NOINTERIOR');
UPDATE players SET gamertag = 'OneNick' WHERE LOWER(gamertag) = LOWER('OneNICK');
UPDATE players SET gamertag = 'Itzzakman' WHERE LOWER(gamertag) = LOWER('itzzakman');
UPDATE players SET gamertag = 'Zetta for 3' WHERE LOWER(gamertag) = LOWER('Zetta For 3');
UPDATE players SET gamertag = 'Paperroute' WHERE LOWER(gamertag) = LOWER('lPaperRoute');
UPDATE players SET gamertag = 'Sleazy hitta' WHERE LOWER(gamertag) = LOWER('SLEAZY HITTA');
UPDATE players SET gamertag = 'Lfadey' WHERE LOWER(gamertag) = LOWER('lFadey');
UPDATE players SET gamertag = 'Nomarw' WHERE LOWER(gamertag) = LOWER('NomarW');
UPDATE players SET gamertag = 'Vnovision' WHERE LOWER(gamertag) = LOWER('vNoVision');
UPDATE players SET gamertag = 'Local mids' WHERE LOWER(gamertag) = LOWER('Local Mids');
UPDATE players SET gamertag = 'Sahrento' WHERE LOWER(gamertag) = LOWER('Sahrento-');
UPDATE players SET gamertag = 'Praise creep' WHERE LOWER(gamertag) = LOWER('Praise Creep');
UPDATE players SET gamertag = 'TimBanz' WHERE LOWER(gamertag) = LOWER('timbanz');
UPDATE players SET gamertag = 'RichoffGrass’s-' WHERE LOWER(gamertag) = LOWER('RICHOFFGRASSS-');
UPDATE players SET gamertag = 'FT_2Clutch' WHERE LOWER(gamertag) = LOWER('FT_2clutch');
UPDATE players SET gamertag = 'Saintsparo' WHERE LOWER(gamertag) = LOWER('SaintSparo');
UPDATE players SET gamertag = 'Yogwi' WHERE LOWER(gamertag) = LOWER('YoGwi');
UPDATE players SET gamertag = 'Dalocky-' WHERE LOWER(gamertag) = LOWER('DaLocky-');
UPDATE players SET gamertag = 'Zploe' WHERE LOWER(gamertag) = LOWER('zPloe');
UPDATE players SET gamertag = 'Lplaynod' WHERE LOWER(gamertag) = LOWER('lPlayNoD');
UPDATE players SET gamertag = 'allhailheem' WHERE LOWER(gamertag) = LOWER('AllHailHeem');
UPDATE players SET gamertag = 'xclarckentx' WHERE LOWER(gamertag) = LOWER('xClarcKentx');
UPDATE players SET gamertag = 'xLTSB' WHERE LOWER(gamertag) = LOWER('XLTSB');
UPDATE players SET gamertag = 'iJPoshy' WHERE LOWER(gamertag) = LOWER('iJposhy');
UPDATE players SET gamertag = 'geekwitdashifts' WHERE LOWER(gamertag) = LOWER('Geekwitdashifts');
UPDATE players SET gamertag = 'is it ovr' WHERE LOWER(gamertag) = LOWER('Is it Ovr');
UPDATE players SET gamertag = 'xicehay' WHERE LOWER(gamertag) = LOWER('xIceHay');
UPDATE players SET gamertag = 'imtheprogram' WHERE LOWER(gamertag) = LOWER('ImTheProgram-');
UPDATE players SET gamertag = 'Nolimit_kev' WHERE LOWER(gamertag) = LOWER('Nolimitkev');
UPDATE players SET gamertag = 'Nolock' WHERE LOWER(gamertag) = LOWER('Nolock-');
UPDATE players SET gamertag = 'Amp110__' WHERE LOWER(gamertag) = LOWER('Amp110');
UPDATE players SET gamertag = 'ZZaytoven' WHERE LOWER(gamertag) = LOWER('zZayToven_');
UPDATE players SET gamertag = 'KingPlamer' WHERE LOWER(gamertag) = LOWER('King Plamer');
UPDATE players SET gamertag = 'Pixare' WHERE LOWER(gamertag) = LOWER('PIXARE-');
UPDATE players SET gamertag = 'Thvef' WHERE LOWER(gamertag) = LOWER('thvef');
UPDATE players SET gamertag = 'Itspolo' WHERE LOWER(gamertag) = LOWER('ItsPolo_-');
UPDATE players SET gamertag = 'LLTwitchLL' WHERE LOWER(gamertag) = LOWER('lltwitchll');
UPDATE players SET gamertag = 'Johnnyfresh21' WHERE LOWER(gamertag) = LOWER('Johnnyfresh21_');
UPDATE players SET gamertag = 'Centerstagerage' WHERE LOWER(gamertag) = LOWER('CenterStageRage');
UPDATE players SET gamertag = 'TtvcrazyIq' WHERE LOWER(gamertag) = LOWER('TTVcrazyiq__');
UPDATE players SET gamertag = 'Zbuiltdifferent' WHERE LOWER(gamertag) = LOWER('Builtdifferent');
UPDATE players SET gamertag = 'Capowya' WHERE LOWER(gamertag) = LOWER('Capowya_');
UPDATE players SET gamertag = 'wastedracks' WHERE LOWER(gamertag) = LOWER('wastedtracks');
UPDATE players SET gamertag = 'iJelly_Fam' WHERE LOWER(gamertag) = LOWER('iJellyy_Fam');
UPDATE players SET gamertag = 'XKezzamo' WHERE LOWER(gamertag) = LOWER('xKezzamo');
UPDATE players SET gamertag = 'Sk8Hardyy' WHERE LOWER(gamertag) = LOWER('SK8Hardyy');
UPDATE players SET gamertag = 'Saint Goud' WHERE LOWER(gamertag) = LOWER('saint goud');
UPDATE players SET gamertag = 'Keylofading' WHERE LOWER(gamertag) = LOWER('KEYLOFADING');
UPDATE players SET gamertag = 'Novatyme' WHERE LOWER(gamertag) = LOWER('NovaTyme');
UPDATE players SET gamertag = 'Noo spacee' WHERE LOWER(gamertag) = LOWER('NOO SPACEE');
UPDATE players SET gamertag = 'Trappaholic' WHERE LOWER(gamertag) = LOWER('TRAPPAHOLIC');
UPDATE players SET gamertag = 'Reset made' WHERE LOWER(gamertag) = LOWER('Reset Made');
UPDATE players SET gamertag = 'JayventersTv' WHERE LOWER(gamertag) = LOWER('JayVentersTV');
UPDATE players SET gamertag = 'Logic_stark' WHERE LOWER(gamertag) = LOWER('Logic_Stark');
UPDATE players SET gamertag = 'ChrisGettin' WHERE LOWER(gamertag) = LOWER('Chrisgettin');
UPDATE players SET gamertag = 'UratRisk' WHERE LOWER(gamertag) = LOWER('UrAtRisk');
UPDATE players SET gamertag = 'Cantguardrobttv__' WHERE LOWER(gamertag) = LOWER('CantGuardRobTTV');
UPDATE players SET gamertag = 'Never goin in' WHERE LOWER(gamertag) = LOWER('Never Goin In');
UPDATE players SET gamertag = 'lowkeygodlike' WHERE LOWER(gamertag) = LOWER('LowkeyGodlike');
UPDATE players SET gamertag = 'firsthalfjayy' WHERE LOWER(gamertag) = LOWER('FirstHalfJay');
UPDATE players SET gamertag = 'ripklutch' WHERE LOWER(gamertag) = LOWER('RIPKLUTCH');
UPDATE players SET gamertag = 'Symelo2K' WHERE LOWER(gamertag) = LOWER('Symelo2k');
UPDATE players SET gamertag = 'AyeMadness' WHERE LOWER(gamertag) = LOWER('AYEMADNESS');
UPDATE players SET gamertag = 'SellingTheGoat' WHERE LOWER(gamertag) = LOWER('SELLINGTHEGOAT');
UPDATE players SET gamertag = 'antfrmny' WHERE LOWER(gamertag) = LOWER('ANTFRMNY');
UPDATE players SET gamertag = 'chiefglox' WHERE LOWER(gamertag) = LOWER('CHIEFGLOX');
UPDATE players SET gamertag = 'HuntTooNice' WHERE LOWER(gamertag) = LOWER('Huntttoonice');
UPDATE players SET gamertag = 'TTVcrazyiq_' WHERE LOWER(gamertag) = LOWER('TTVcrazyiq__');
UPDATE players SET gamertag = 'NoLimitNXT' WHERE LOWER(gamertag) = LOWER('NoLimit NXT');
UPDATE players SET gamertag = 'Pastor Jam ieW' WHERE LOWER(gamertag) = LOWER('Pastor JamieW');
UPDATE players SET gamertag = 'CJ OnDeck' WHERE LOWER(gamertag) = LOWER('CJ_OnDeck');
UPDATE players SET gamertag = 'DemDollak' WHERE LOWER(gamertag) = LOWER('DemDollaK');
UPDATE players SET gamertag = 'UndottedCepin' WHERE LOWER(gamertag) = LOWER('undotted cepin');
UPDATE players SET gamertag = 'kobi---TV' WHERE LOWER(gamertag) = LOWER('Kobi--TV');
UPDATE players SET gamertag = 'T0mest' WHERE LOWER(gamertag) = LOWER('t0mest__');
UPDATE players SET gamertag = 'KostaGoated' WHERE LOWER(gamertag) = LOWER('IKostaGoated');
UPDATE players SET gamertag = 'IsoTayy' WHERE LOWER(gamertag) = LOWER('IsoTayy_');
UPDATE players SET gamertag = 'WTFL_ZAHID' WHERE LOWER(gamertag) = LOWER('WTFL ZAHID');
UPDATE players SET gamertag = 'xKujman' WHERE LOWER(gamertag) = LOWER('XKujman');
UPDATE players SET gamertag = 'IIEladI' WHERE LOWER(gamertag) = LOWER('IIEladi');
UPDATE players SET gamertag = 'Vscorpi __' WHERE LOWER(gamertag) = LOWER('vScorpi__');
UPDATE players SET gamertag = 'vclutch4fun' WHERE LOWER(gamertag) = LOWER('vClutch4Fun');
UPDATE players SET gamertag = 'Daboizerko' WHERE LOWER(gamertag) = LOWER('DaboiZerko');
UPDATE players SET gamertag = 'Pedrobinho__' WHERE LOWER(gamertag) = LOWER('Pedrobinho');
UPDATE players SET gamertag = 'Boxoutbaba' WHERE LOWER(gamertag) = LOWER('BoxOutBaba');
UPDATE players SET gamertag = 'Etimmvi' WHERE LOWER(gamertag) = LOWER('EtiMMVI');
UPDATE players SET gamertag = 'RykiiQ' WHERE LOWER(gamertag) = LOWER('RyKiiQ');
UPDATE players SET gamertag = 'RIPxRebs' WHERE LOWER(gamertag) = LOWER('RIPXRebs');
UPDATE players SET gamertag = 'playb0i-_Flxshy' WHERE LOWER(gamertag) = LOWER('playb0i_Flxshy');
UPDATE players SET gamertag = 'IIWHOOPTYDOO' WHERE LOWER(gamertag) = LOWER('II WHOOPTYDOO');
UPDATE players SET gamertag = 'HezTC' WHERE LOWER(gamertag) = LOWER('Hez TC');
UPDATE players SET gamertag = 'IIICROWNII' WHERE LOWER(gamertag) = LOWER('IIICROWNIII');
UPDATE players SET gamertag = 'ReefGeekin' WHERE LOWER(gamertag) = LOWER('ReefGeekin-');
UPDATE players SET gamertag = 'DameDash' WHERE LOWER(gamertag) = LOWER('DameDash_');
UPDATE players SET gamertag = 'thurl moon' WHERE LOWER(gamertag) = LOWER('Thurl Moon');
UPDATE players SET gamertag = 'iBalLRekk' WHERE LOWER(gamertag) = LOWER('iBall_Rekk');
UPDATE players SET gamertag = 'Eternal Pep' WHERE LOWER(gamertag) = LOWER('EternalPep');
UPDATE players SET gamertag = 'PazValdez' WHERE LOWER(gamertag) = LOWER('pazvaldez');
UPDATE players SET gamertag = 'Activeyoga' WHERE LOWER(gamertag) = LOWER('ActiveYogaa');
UPDATE players SET gamertag = 'ikofyou' WHERE LOWER(gamertag) = LOWER('ik of you');
UPDATE players SET gamertag = 'Itspolo_' WHERE LOWER(gamertag) = LOWER('ItsPolo_-');
UPDATE players SET gamertag = 'CR_Vonte' WHERE LOWER(gamertag) = LOWER('Cr vonte');
UPDATE players SET gamertag = 'SwitzosnTTV' WHERE LOWER(gamertag) = LOWER('SWITZOSN TTV');
UPDATE players SET gamertag = 'BeezyTC' WHERE LOWER(gamertag) = LOWER('Beezy TC');
UPDATE players SET gamertag = 'SOBxSharky11' WHERE LOWER(gamertag) = LOWER('SOBxSHARKY11');
UPDATE players SET gamertag = 'IIswipez' WHERE LOWER(gamertag) = LOWER('IISwipez');
UPDATE players SET gamertag = 'Hatedpotential' WHERE LOWER(gamertag) = LOWER('HatedPotential');
UPDATE players SET gamertag = 'SincerelyTayy' WHERE LOWER(gamertag) = LOWER('SincerlyTayy');
UPDATE players SET gamertag = 'En_Mode_Z' WHERE LOWER(gamertag) = LOWER('En_Mode__Z');
UPDATE players SET gamertag = 'o iHOOP5 o' WHERE LOWER(gamertag) = LOWER('o_ihoop5_o');

COMMIT;
